from enum import Enum


class ErrCode(str, Enum):
    FILE_EXT_NOT_ALLOWED = "FILE_EXT_NOT_ALLOWED"
    FILE_NAME_TAKEN = "FILE_NAME_TAKEN"
    FILE_PATH_INCORRECT = "FILE_PATH_INCORRECT"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_NOT_LINKED_TO_PROJECT = "FILE_NOT_LINKED_TO_PROJECT"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_NOT_DELETED = "PROJECT_NOT_DELETED"
