// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  CheckHealthApiV1SystemHealthGetData,
  CheckHealthApiV1SystemHealthGetResponses,
  CreateJobApiV1ProjectsProjectIdJobsPostData,
  CreateJobApiV1ProjectsProjectIdJobsPostErrors,
  CreateJobApiV1ProjectsProjectIdJobsPostResponses,
  CreateProjectApiV1ProjectsPostData,
  CreateProjectApiV1ProjectsPostErrors,
  CreateProjectApiV1ProjectsPostResponses,
  DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteData,
  DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteErrors,
  DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteResponses,
  GetFileApiV1ProjectsProjectIdFilesFileIdGetData,
  GetFileApiV1ProjectsProjectIdFilesFileIdGetErrors,
  GetFileApiV1ProjectsProjectIdFilesFileIdGetResponses,
  GetJobApiV1ProjectsProjectIdJobsJobIdGetData,
  GetJobApiV1ProjectsProjectIdJobsJobIdGetErrors,
  GetJobApiV1ProjectsProjectIdJobsJobIdGetResponses,
  GetProjectApiV1ProjectsProjectIdGetData,
  GetProjectApiV1ProjectsProjectIdGetErrors,
  GetProjectApiV1ProjectsProjectIdGetResponses,
  GetVersionApiV1SystemVersionGetData,
  GetVersionApiV1SystemVersionGetResponses,
  HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteData,
  HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteErrors,
  HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteResponses,
  ListFilesApiV1ProjectsProjectIdFilesGetData,
  ListFilesApiV1ProjectsProjectIdFilesGetErrors,
  ListFilesApiV1ProjectsProjectIdFilesGetResponses,
  ListJobsApiV1ProjectsProjectIdJobsGetData,
  ListJobsApiV1ProjectsProjectIdJobsGetErrors,
  ListJobsApiV1ProjectsProjectIdJobsGetResponses,
  ListProjectsApiV1ProjectsGetData,
  ListProjectsApiV1ProjectsGetResponses,
  ListTrashApiV1ProjectsTrashGetData,
  ListTrashApiV1ProjectsTrashGetResponses,
  RegisterFileApiV1ProjectsProjectIdFilesRegisterPostData,
  RegisterFileApiV1ProjectsProjectIdFilesRegisterPostErrors,
  RegisterFileApiV1ProjectsProjectIdFilesRegisterPostResponses,
  RestoreProjectApiV1ProjectsProjectIdRestorePatchData,
  RestoreProjectApiV1ProjectsProjectIdRestorePatchErrors,
  RestoreProjectApiV1ProjectsProjectIdRestorePatchResponses,
  SoftDeleteProjectApiV1ProjectsProjectIdDeleteData,
  SoftDeleteProjectApiV1ProjectsProjectIdDeleteErrors,
  SoftDeleteProjectApiV1ProjectsProjectIdDeleteResponses,
  UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchData,
  UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchErrors,
  UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchResponses,
  UploadFileApiV1ProjectsProjectIdFilesPostData,
  UploadFileApiV1ProjectsProjectIdFilesPostErrors,
  UploadFileApiV1ProjectsProjectIdFilesPostResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Register File
 */
export const registerFileApiV1ProjectsProjectIdFilesRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RegisterFileApiV1ProjectsProjectIdFilesRegisterPostData,
    ThrowOnError
  >
): RequestResult<
  RegisterFileApiV1ProjectsProjectIdFilesRegisterPostResponses,
  RegisterFileApiV1ProjectsProjectIdFilesRegisterPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterFileApiV1ProjectsProjectIdFilesRegisterPostResponses,
    RegisterFileApiV1ProjectsProjectIdFilesRegisterPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/files/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List Files
 */
export const listFilesApiV1ProjectsProjectIdFilesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListFilesApiV1ProjectsProjectIdFilesGetData, ThrowOnError>
): RequestResult<
  ListFilesApiV1ProjectsProjectIdFilesGetResponses,
  ListFilesApiV1ProjectsProjectIdFilesGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListFilesApiV1ProjectsProjectIdFilesGetResponses,
    ListFilesApiV1ProjectsProjectIdFilesGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/files", ...options })

/**
 * Upload File
 */
export const uploadFileApiV1ProjectsProjectIdFilesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UploadFileApiV1ProjectsProjectIdFilesPostData, ThrowOnError>
): RequestResult<
  UploadFileApiV1ProjectsProjectIdFilesPostResponses,
  UploadFileApiV1ProjectsProjectIdFilesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UploadFileApiV1ProjectsProjectIdFilesPostResponses,
    UploadFileApiV1ProjectsProjectIdFilesPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/api/v1/projects/{project_id}/files",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Delete File
 */
export const deleteFileApiV1ProjectsProjectIdFilesFileIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteData, ThrowOnError>
): RequestResult<
  DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteResponses,
  DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteResponses,
    DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/files/{file_id}", ...options })

/**
 * Get File
 */
export const getFileApiV1ProjectsProjectIdFilesFileIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFileApiV1ProjectsProjectIdFilesFileIdGetData, ThrowOnError>
): RequestResult<
  GetFileApiV1ProjectsProjectIdFilesFileIdGetResponses,
  GetFileApiV1ProjectsProjectIdFilesFileIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetFileApiV1ProjectsProjectIdFilesFileIdGetResponses,
    GetFileApiV1ProjectsProjectIdFilesFileIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/files/{file_id}", ...options })

/**
 * Update File
 */
export const updateFileApiV1ProjectsProjectIdFilesFileIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchData, ThrowOnError>
): RequestResult<
  UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchResponses,
  UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchResponses,
    UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/files/{file_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List Jobs
 */
export const listJobsApiV1ProjectsProjectIdJobsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListJobsApiV1ProjectsProjectIdJobsGetData, ThrowOnError>
): RequestResult<
  ListJobsApiV1ProjectsProjectIdJobsGetResponses,
  ListJobsApiV1ProjectsProjectIdJobsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListJobsApiV1ProjectsProjectIdJobsGetResponses,
    ListJobsApiV1ProjectsProjectIdJobsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/jobs", ...options })

/**
 * Create Job
 */
export const createJobApiV1ProjectsProjectIdJobsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateJobApiV1ProjectsProjectIdJobsPostData, ThrowOnError>
): RequestResult<
  CreateJobApiV1ProjectsProjectIdJobsPostResponses,
  CreateJobApiV1ProjectsProjectIdJobsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateJobApiV1ProjectsProjectIdJobsPostResponses,
    CreateJobApiV1ProjectsProjectIdJobsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/{project_id}/jobs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get Job
 */
export const getJobApiV1ProjectsProjectIdJobsJobIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetJobApiV1ProjectsProjectIdJobsJobIdGetData, ThrowOnError>
): RequestResult<
  GetJobApiV1ProjectsProjectIdJobsJobIdGetResponses,
  GetJobApiV1ProjectsProjectIdJobsJobIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetJobApiV1ProjectsProjectIdJobsJobIdGetResponses,
    GetJobApiV1ProjectsProjectIdJobsJobIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/jobs/{job_id}", ...options })

/**
 * List Projects
 */
export const listProjectsApiV1ProjectsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListProjectsApiV1ProjectsGetData, ThrowOnError>
): RequestResult<ListProjectsApiV1ProjectsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListProjectsApiV1ProjectsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/projects/", ...options })

/**
 * Create Project
 */
export const createProjectApiV1ProjectsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateProjectApiV1ProjectsPostData, ThrowOnError>
): RequestResult<
  CreateProjectApiV1ProjectsPostResponses,
  CreateProjectApiV1ProjectsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProjectApiV1ProjectsPostResponses,
    CreateProjectApiV1ProjectsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/projects/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List Trash
 */
export const listTrashApiV1ProjectsTrashGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListTrashApiV1ProjectsTrashGetData, ThrowOnError>
): RequestResult<ListTrashApiV1ProjectsTrashGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListTrashApiV1ProjectsTrashGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/projects/trash", ...options })

/**
 * Soft Delete Project
 */
export const softDeleteProjectApiV1ProjectsProjectIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SoftDeleteProjectApiV1ProjectsProjectIdDeleteData, ThrowOnError>
): RequestResult<
  SoftDeleteProjectApiV1ProjectsProjectIdDeleteResponses,
  SoftDeleteProjectApiV1ProjectsProjectIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    SoftDeleteProjectApiV1ProjectsProjectIdDeleteResponses,
    SoftDeleteProjectApiV1ProjectsProjectIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}", ...options })

/**
 * Get Project
 */
export const getProjectApiV1ProjectsProjectIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProjectApiV1ProjectsProjectIdGetData, ThrowOnError>
): RequestResult<
  GetProjectApiV1ProjectsProjectIdGetResponses,
  GetProjectApiV1ProjectsProjectIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProjectApiV1ProjectsProjectIdGetResponses,
    GetProjectApiV1ProjectsProjectIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}", ...options })

/**
 * Hard Delete Project
 */
export const hardDeleteProjectApiV1ProjectsProjectIdPermanentDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteData,
    ThrowOnError
  >
): RequestResult<
  HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteResponses,
  HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteResponses,
    HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/permanent", ...options })

/**
 * Restore Project
 */
export const restoreProjectApiV1ProjectsProjectIdRestorePatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RestoreProjectApiV1ProjectsProjectIdRestorePatchData, ThrowOnError>
): RequestResult<
  RestoreProjectApiV1ProjectsProjectIdRestorePatchResponses,
  RestoreProjectApiV1ProjectsProjectIdRestorePatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    RestoreProjectApiV1ProjectsProjectIdRestorePatchResponses,
    RestoreProjectApiV1ProjectsProjectIdRestorePatchErrors,
    ThrowOnError
  >({ url: "/api/v1/projects/{project_id}/restore", ...options })

/**
 * Check Health
 */
export const checkHealthApiV1SystemHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<CheckHealthApiV1SystemHealthGetData, ThrowOnError>
): RequestResult<CheckHealthApiV1SystemHealthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    CheckHealthApiV1SystemHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/system/health", ...options })

/**
 * Get Version
 */
export const getVersionApiV1SystemVersionGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetVersionApiV1SystemVersionGetData, ThrowOnError>
): RequestResult<GetVersionApiV1SystemVersionGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetVersionApiV1SystemVersionGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/system/version", ...options })
