// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {})
}

/**
 * Body_upload_file_api_v1_projects__project_id__files_post
 */
export type BodyUploadFileApiV1ProjectsProjectIdFilesPost = {
  /**
   * File
   */
  file: Blob | File
  /**
   * File Type
   */
  file_type?: string
}

/**
 * FileRegister
 */
export type FileRegister = {
  /**
   * Path
   */
  path: string
  /**
   * File Type
   */
  file_type?: string
}

/**
 * FileResponse
 */
export type FileResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Project Id
   */
  project_id: string
  /**
   * Filename
   */
  filename: string
  /**
   * File Type
   */
  file_type: string
  /**
   * Status
   */
  status: string
  /**
   * Job Id
   */
  job_id: string | null
  /**
   * Size Bytes
   */
  size_bytes: number
  /**
   * Created At
   */
  created_at: string
}

/**
 * FileUpdate
 */
export type FileUpdate = {
  /**
   * File Type
   */
  file_type?: string | null
  /**
   * Filename
   */
  filename?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * HealthResponse
 */
export type HealthResponse = {
  /**
   * Status
   */
  status: string
}

/**
 * JobCreate
 */
export type JobCreate = {
  /**
   * Analysis Type
   */
  analysis_type?: string
}

/**
 * JobResponse
 */
export type JobResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Project Id
   */
  project_id: string
  /**
   * Analysis Type
   */
  analysis_type: string
  /**
   * Status
   */
  status: string
  /**
   * Step
   */
  step: string
  /**
   * Progress
   */
  progress: number
  /**
   * Message
   */
  message: string
  /**
   * Results Meta
   */
  results_meta: {
    [key: string]: unknown
  } | null
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * ProjectCreate
 */
export type ProjectCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Workspace Path
   */
  workspace_path?: string | null
}

/**
 * ProjectResponse
 */
export type ProjectResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string | null
  /**
   * Workspace Path
   */
  workspace_path: string | null
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Deleted At
   */
  deleted_at: string | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

/**
 * VersionResponse
 */
export type VersionResponse = {
  /**
   * Server
   */
  server: string
  /**
   * Cellmetpro
   */
  cellmetpro: string
}

export type RegisterFileApiV1ProjectsProjectIdFilesRegisterPostData = {
  body: FileRegister
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/files/register"
}

export type RegisterFileApiV1ProjectsProjectIdFilesRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RegisterFileApiV1ProjectsProjectIdFilesRegisterPostError =
  RegisterFileApiV1ProjectsProjectIdFilesRegisterPostErrors[keyof RegisterFileApiV1ProjectsProjectIdFilesRegisterPostErrors]

export type RegisterFileApiV1ProjectsProjectIdFilesRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: FileResponse
}

export type RegisterFileApiV1ProjectsProjectIdFilesRegisterPostResponse =
  RegisterFileApiV1ProjectsProjectIdFilesRegisterPostResponses[keyof RegisterFileApiV1ProjectsProjectIdFilesRegisterPostResponses]

export type ListFilesApiV1ProjectsProjectIdFilesGetData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/files"
}

export type ListFilesApiV1ProjectsProjectIdFilesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListFilesApiV1ProjectsProjectIdFilesGetError =
  ListFilesApiV1ProjectsProjectIdFilesGetErrors[keyof ListFilesApiV1ProjectsProjectIdFilesGetErrors]

export type ListFilesApiV1ProjectsProjectIdFilesGetResponses = {
  /**
   * Response List Files Api V1 Projects  Project Id  Files Get
   *
   * Successful Response
   */
  200: Array<FileResponse>
}

export type ListFilesApiV1ProjectsProjectIdFilesGetResponse =
  ListFilesApiV1ProjectsProjectIdFilesGetResponses[keyof ListFilesApiV1ProjectsProjectIdFilesGetResponses]

export type UploadFileApiV1ProjectsProjectIdFilesPostData = {
  body: BodyUploadFileApiV1ProjectsProjectIdFilesPost
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/files"
}

export type UploadFileApiV1ProjectsProjectIdFilesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UploadFileApiV1ProjectsProjectIdFilesPostError =
  UploadFileApiV1ProjectsProjectIdFilesPostErrors[keyof UploadFileApiV1ProjectsProjectIdFilesPostErrors]

export type UploadFileApiV1ProjectsProjectIdFilesPostResponses = {
  /**
   * Successful Response
   */
  200: FileResponse
}

export type UploadFileApiV1ProjectsProjectIdFilesPostResponse =
  UploadFileApiV1ProjectsProjectIdFilesPostResponses[keyof UploadFileApiV1ProjectsProjectIdFilesPostResponses]

export type DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
    /**
     * File Id
     */
    file_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/files/{file_id}"
}

export type DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteError =
  DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteErrors[keyof DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteErrors]

export type DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteResponse =
  DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteResponses[keyof DeleteFileApiV1ProjectsProjectIdFilesFileIdDeleteResponses]

export type GetFileApiV1ProjectsProjectIdFilesFileIdGetData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
    /**
     * File Id
     */
    file_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/files/{file_id}"
}

export type GetFileApiV1ProjectsProjectIdFilesFileIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetFileApiV1ProjectsProjectIdFilesFileIdGetError =
  GetFileApiV1ProjectsProjectIdFilesFileIdGetErrors[keyof GetFileApiV1ProjectsProjectIdFilesFileIdGetErrors]

export type GetFileApiV1ProjectsProjectIdFilesFileIdGetResponses = {
  /**
   * Successful Response
   */
  200: FileResponse
}

export type GetFileApiV1ProjectsProjectIdFilesFileIdGetResponse =
  GetFileApiV1ProjectsProjectIdFilesFileIdGetResponses[keyof GetFileApiV1ProjectsProjectIdFilesFileIdGetResponses]

export type UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchData = {
  body: FileUpdate
  path: {
    /**
     * Project Id
     */
    project_id: string
    /**
     * File Id
     */
    file_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/files/{file_id}"
}

export type UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchError =
  UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchErrors[keyof UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchErrors]

export type UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchResponses = {
  /**
   * Successful Response
   */
  200: FileResponse
}

export type UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchResponse =
  UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchResponses[keyof UpdateFileApiV1ProjectsProjectIdFilesFileIdPatchResponses]

export type ListJobsApiV1ProjectsProjectIdJobsGetData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/jobs"
}

export type ListJobsApiV1ProjectsProjectIdJobsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListJobsApiV1ProjectsProjectIdJobsGetError =
  ListJobsApiV1ProjectsProjectIdJobsGetErrors[keyof ListJobsApiV1ProjectsProjectIdJobsGetErrors]

export type ListJobsApiV1ProjectsProjectIdJobsGetResponses = {
  /**
   * Response List Jobs Api V1 Projects  Project Id  Jobs Get
   *
   * Successful Response
   */
  200: Array<JobResponse>
}

export type ListJobsApiV1ProjectsProjectIdJobsGetResponse =
  ListJobsApiV1ProjectsProjectIdJobsGetResponses[keyof ListJobsApiV1ProjectsProjectIdJobsGetResponses]

export type CreateJobApiV1ProjectsProjectIdJobsPostData = {
  body: JobCreate
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/jobs"
}

export type CreateJobApiV1ProjectsProjectIdJobsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateJobApiV1ProjectsProjectIdJobsPostError =
  CreateJobApiV1ProjectsProjectIdJobsPostErrors[keyof CreateJobApiV1ProjectsProjectIdJobsPostErrors]

export type CreateJobApiV1ProjectsProjectIdJobsPostResponses = {
  /**
   * Successful Response
   */
  200: JobResponse
}

export type CreateJobApiV1ProjectsProjectIdJobsPostResponse =
  CreateJobApiV1ProjectsProjectIdJobsPostResponses[keyof CreateJobApiV1ProjectsProjectIdJobsPostResponses]

export type GetJobApiV1ProjectsProjectIdJobsJobIdGetData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
    /**
     * Job Id
     */
    job_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/jobs/{job_id}"
}

export type GetJobApiV1ProjectsProjectIdJobsJobIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetJobApiV1ProjectsProjectIdJobsJobIdGetError =
  GetJobApiV1ProjectsProjectIdJobsJobIdGetErrors[keyof GetJobApiV1ProjectsProjectIdJobsJobIdGetErrors]

export type GetJobApiV1ProjectsProjectIdJobsJobIdGetResponses = {
  /**
   * Successful Response
   */
  200: JobResponse
}

export type GetJobApiV1ProjectsProjectIdJobsJobIdGetResponse =
  GetJobApiV1ProjectsProjectIdJobsJobIdGetResponses[keyof GetJobApiV1ProjectsProjectIdJobsJobIdGetResponses]

export type ListProjectsApiV1ProjectsGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/projects/"
}

export type ListProjectsApiV1ProjectsGetResponses = {
  /**
   * Response List Projects Api V1 Projects  Get
   *
   * Successful Response
   */
  200: Array<ProjectResponse>
}

export type ListProjectsApiV1ProjectsGetResponse =
  ListProjectsApiV1ProjectsGetResponses[keyof ListProjectsApiV1ProjectsGetResponses]

export type CreateProjectApiV1ProjectsPostData = {
  body: ProjectCreate
  path?: never
  query?: never
  url: "/api/v1/projects/"
}

export type CreateProjectApiV1ProjectsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateProjectApiV1ProjectsPostError =
  CreateProjectApiV1ProjectsPostErrors[keyof CreateProjectApiV1ProjectsPostErrors]

export type CreateProjectApiV1ProjectsPostResponses = {
  /**
   * Successful Response
   */
  201: ProjectResponse
}

export type CreateProjectApiV1ProjectsPostResponse =
  CreateProjectApiV1ProjectsPostResponses[keyof CreateProjectApiV1ProjectsPostResponses]

export type ListTrashApiV1ProjectsTrashGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/projects/trash"
}

export type ListTrashApiV1ProjectsTrashGetResponses = {
  /**
   * Response List Trash Api V1 Projects Trash Get
   *
   * Successful Response
   */
  200: Array<ProjectResponse>
}

export type ListTrashApiV1ProjectsTrashGetResponse =
  ListTrashApiV1ProjectsTrashGetResponses[keyof ListTrashApiV1ProjectsTrashGetResponses]

export type SoftDeleteProjectApiV1ProjectsProjectIdDeleteData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}"
}

export type SoftDeleteProjectApiV1ProjectsProjectIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SoftDeleteProjectApiV1ProjectsProjectIdDeleteError =
  SoftDeleteProjectApiV1ProjectsProjectIdDeleteErrors[keyof SoftDeleteProjectApiV1ProjectsProjectIdDeleteErrors]

export type SoftDeleteProjectApiV1ProjectsProjectIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type SoftDeleteProjectApiV1ProjectsProjectIdDeleteResponse =
  SoftDeleteProjectApiV1ProjectsProjectIdDeleteResponses[keyof SoftDeleteProjectApiV1ProjectsProjectIdDeleteResponses]

export type GetProjectApiV1ProjectsProjectIdGetData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}"
}

export type GetProjectApiV1ProjectsProjectIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetProjectApiV1ProjectsProjectIdGetError =
  GetProjectApiV1ProjectsProjectIdGetErrors[keyof GetProjectApiV1ProjectsProjectIdGetErrors]

export type GetProjectApiV1ProjectsProjectIdGetResponses = {
  /**
   * Successful Response
   */
  200: ProjectResponse
}

export type GetProjectApiV1ProjectsProjectIdGetResponse =
  GetProjectApiV1ProjectsProjectIdGetResponses[keyof GetProjectApiV1ProjectsProjectIdGetResponses]

export type HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/permanent"
}

export type HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteError =
  HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteErrors[keyof HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteErrors]

export type HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteResponse =
  HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteResponses[keyof HardDeleteProjectApiV1ProjectsProjectIdPermanentDeleteResponses]

export type RestoreProjectApiV1ProjectsProjectIdRestorePatchData = {
  body?: never
  path: {
    /**
     * Project Id
     */
    project_id: string
  }
  query?: never
  url: "/api/v1/projects/{project_id}/restore"
}

export type RestoreProjectApiV1ProjectsProjectIdRestorePatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RestoreProjectApiV1ProjectsProjectIdRestorePatchError =
  RestoreProjectApiV1ProjectsProjectIdRestorePatchErrors[keyof RestoreProjectApiV1ProjectsProjectIdRestorePatchErrors]

export type RestoreProjectApiV1ProjectsProjectIdRestorePatchResponses = {
  /**
   * Successful Response
   */
  200: ProjectResponse
}

export type RestoreProjectApiV1ProjectsProjectIdRestorePatchResponse =
  RestoreProjectApiV1ProjectsProjectIdRestorePatchResponses[keyof RestoreProjectApiV1ProjectsProjectIdRestorePatchResponses]

export type CheckHealthApiV1SystemHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/system/health"
}

export type CheckHealthApiV1SystemHealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse
}

export type CheckHealthApiV1SystemHealthGetResponse =
  CheckHealthApiV1SystemHealthGetResponses[keyof CheckHealthApiV1SystemHealthGetResponses]

export type GetVersionApiV1SystemVersionGetData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/system/version"
}

export type GetVersionApiV1SystemVersionGetResponses = {
  /**
   * Successful Response
   */
  200: VersionResponse
}

export type GetVersionApiV1SystemVersionGetResponse =
  GetVersionApiV1SystemVersionGetResponses[keyof GetVersionApiV1SystemVersionGetResponses]
